// <auto-generated />
using System;
using AspnetCoreMvcFull.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspnetCoreMvcFull.Migrations
{
    [DbContext(typeof(ManagmentRfidDbContext))]
    [Migration("20241130203055_finish")]
    partial class finish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Administrador", b =>
                {
                    b.Property<int>("IdAdministrador")
                        .HasColumnType("int");

                    b.Property<string>("AreaTrabajo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdAdministrador")
                        .HasName("PK__Administ__2B3E34A8F6D2610D");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdAlumno")
                        .HasName("PK__Alumno__460B474052CAE741");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Alumno", (string)null);
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Asistencium", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdRegistro")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("IdAsistencia")
                        .HasName("PK__Asistenc__3956DEE6FF26E3B5");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdRegistro");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGrupo")
                        .HasName("PK__Grupo__303F6FD992EB38A6");

                    b.HasIndex("IdMateria");

                    b.ToTable("Grupo", (string)null);
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Materium", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<int>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMateria")
                        .HasName("PK__Materia__EC174670A96156B2");

                    b.HasIndex("IdProfesor");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Profesor", b =>
                {
                    b.Property<int>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdProfesor")
                        .HasName("PK__Profesor__C377C3A103C2895A");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Profesor", (string)null);
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Registro", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.HasKey("IdRegistro")
                        .HasName("PK__Registro__FFA45A99602B90CC");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Registro", (string)null);
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Rfid", b =>
                {
                    b.Property<int>("IdRfid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRFID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRfid"));

                    b.Property<string>("CodigoRfid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoRFID");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.HasKey("IdRfid")
                        .HasName("PK__RFID__B50B632619B56212");

                    b.HasIndex("IdAlumno");

                    b.HasIndex(new[] { "CodigoRfid" }, "UQ__RFID__117C4055AD60DE98")
                        .IsUnique();

                    b.ToTable("RFID", (string)null);
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__2A49584C47B6BA5F");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97B97743B9");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuario__60695A19159A751F")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("GrupoAlumno", b =>
                {
                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.HasKey("IdGrupo", "IdAlumno")
                        .HasName("PK__Grupo_Al__245FDBADDC592434");

                    b.HasIndex("IdAlumno");

                    b.ToTable("Grupo_Alumno", (string)null);
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Administrador", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Administradors")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Administr__IdUsu__5629CD9C");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Alumno", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Alumnos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Alumno__IdUsuari__534D60F1");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Asistencium", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Alumno", "IdAlumnoNavigation")
                        .WithMany("Asistencia")
                        .HasForeignKey("IdAlumno")
                        .IsRequired()
                        .HasConstraintName("FK__Asistenci__IdAlu__6754599E");

                    b.HasOne("AspnetCoreMvcFull.Models.Registro", "IdRegistroNavigation")
                        .WithMany("Asistencia")
                        .HasForeignKey("IdRegistro")
                        .IsRequired()
                        .HasConstraintName("FK__Asistenci__IdReg__66603565");

                    b.Navigation("IdAlumnoNavigation");

                    b.Navigation("IdRegistroNavigation");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Grupo", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Materium", "IdMateriaNavigation")
                        .WithMany("Grupos")
                        .HasForeignKey("IdMateria")
                        .IsRequired()
                        .HasConstraintName("FK__Grupo__IdMateria__5FB337D6");

                    b.Navigation("IdMateriaNavigation");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Materium", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Profesor", "IdProfesorNavigation")
                        .WithMany("Materia")
                        .HasForeignKey("IdProfesor")
                        .IsRequired()
                        .HasConstraintName("FK__Materia__IdProfe__5CD6CB2B");

                    b.Navigation("IdProfesorNavigation");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Profesor", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Profesors")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Profesor__IdUsua__5070F446");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Registro", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Grupo", "IdGrupoNavigation")
                        .WithMany("Registros")
                        .HasForeignKey("IdGrupo")
                        .IsRequired()
                        .HasConstraintName("FK__Registro__IdGrup__628FA481");

                    b.Navigation("IdGrupoNavigation");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Rfid", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Alumno", "IdAlumnoNavigation")
                        .WithMany("Rfids")
                        .HasForeignKey("IdAlumno")
                        .IsRequired()
                        .HasConstraintName("FK__RFID__IdAlumno__59FA5E80");

                    b.Navigation("IdAlumnoNavigation");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Usuario", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__IdRol__4D94879B");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("GrupoAlumno", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Alumno", null)
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .IsRequired()
                        .HasConstraintName("FK__Grupo_Alu__IdAlu__6B24EA82");

                    b.HasOne("AspnetCoreMvcFull.Models.Grupo", null)
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .IsRequired()
                        .HasConstraintName("FK__Grupo_Alu__IdGru__6A30C649");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Alumno", b =>
                {
                    b.Navigation("Asistencia");

                    b.Navigation("Rfids");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Grupo", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Materium", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Profesor", b =>
                {
                    b.Navigation("Materia");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Registro", b =>
                {
                    b.Navigation("Asistencia");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Usuario", b =>
                {
                    b.Navigation("Administradors");

                    b.Navigation("Alumnos");

                    b.Navigation("Profesors");
                });
#pragma warning restore 612, 618
        }
    }
}
